### PR TITLE
Add Fedora 29

### PR DESCRIPTION
**Pull request by c72578**

### CODE REVIEW

**Comment by AMDmi3** [comment]
It replies with 403

https://mirror.yandex.ru/fedora/linux/releases/29/

**Comment by c72578** [comment]
Fedora 29 was officially released on 2018-10-30, so it is only a question of time, until mirror.yandex.ru is synchronized and permission granted.

**Comment by c72578** [comment]
It is OK now.

**Comment by AMDmi3** [comment]
Merged

**Pull request closed without merging**
