### PR TITLE
Improvements for Antergos Repos

### PR DESCRIPTION
**Pull request by lots0logs**

### CODE REVIEW

**Comment by AMDmi3** [comment]
Um, these look like separate repos.

**Comment by lots0logs** [comment]
Not sure what you mean?

**Comment by AMDmi3** [comment]
These contain intersecting sets of packages, so they are not subrepositories like e.g debian main/contrib/non-free, but separate repos like debian stable/experimental are. They should not be merged.

**Comment by lots0logs** [comment]
I didn't realize that was the expectation. It just seems like it makes more sense to have them together because there is really only one repo. The staging repo is just that..staging..no package stays there for longer than a few days usually. Maybe its better to remove staging altogether?

**Comment by AMDmi3** [comment]
> It just seems like it makes more sense to have them together because there is really only one repo. The staging repo is just that..staging..no package stays there for longer than a few days usually

It's the same as with Debian Experimental. It is a separate repo, you can compare package versions between it and main repo, you can watch package move from staging to main, users (I assume) can enable main, or main+staging if they are eager to test freshest versions.

> Maybe its better to remove staging altogether?

No, staging is actually the most valuable for repology as newest versions appear there first.

So let's leave both repos there, I'll gladly merge link-related improvements.

**Comment by lots0logs** [comment]
@AMDmi3 Done :white_check_mark:

**Pull request merged**
