### PR TITLE
Add AOSC maintainers

### PR DESCRIPTION
**Pull request by gumblex**
The packages site added support for showing maintainers (git committer) recently.

### CODE REVIEW

**Comment by AMDmi3** [comment]
There are 5 packages with suspicious `"committer" : "GitHub <noreply@github.com>"`. What are these, shouldn't it be ignored?

**Comment by gumblex** [comment]
These are regular packages. Perhaps the committer wants to remain anonymous.

**Comment by gumblex** [comment]
The packager says it came from Github web edits.

**Comment by AMDmi3** [comment]
Hmm, it should fill in your name/email, as long as you have them filled in. Anyway, I'll leave these be.

**Pull request merged**
