### PR TITLE
also merge names for other hledger packages

### PR DESCRIPTION
**Pull request by simonmichael**
-ui, -web, -lib, -interest etc.

### CODE REVIEW

**Comment by AMDmi3** [comment]
Why not `namepat: "haskell:(hledger(?:-.+))", setname: "$1"` or just `namepat: "haskell:(hledger.*)", setname: "$1"`. Also is it correct to remove haskell: from all of them? I tend to remove languare prefixes for utilities, and at least hledger-lib is probably just the module

**Comment by simonmichael** [comment]
@AMDmi3 I kept it simple to be obviously correct. Yes perhaps you're right about hledger-lib, it's the only one not providing an end-user tool. So I will probably do:
```
haskell:hledger(.*) -> $1
hledger-lib -> haskell:hledger-lib
```
? (Unless this works: `haskell:hledger(?!:-lib)` ?)

**Comment by simonmichael** [comment]
Notifications may have been unclear: there's a cleaned-up commit 52fda5b here.

**Comment by simonmichael** [comment]
Thanks @AMDmi3. I read that the site updates hourly but https://repology.org/metapackage/hledger/badges and https://repology.org/metapackage/haskell:hledger/badges look the same. I wonder if this is working ?

**Comment by AMDmi3** [comment]
The regexp was incorrect, in fact it has broken update for other repos - it turns that (?!) lookagead construct does not generate capture, so using `$1` in setname was incorrect. I've fixed it by splitting into two rules.

**Comment by simonmichael** [comment]
Thanks. And, thanks for repology, it's great!

**Pull request merged**
