### PR TITLE
add `rindeal` ebuild repository

### PR DESCRIPTION
**Pull request by rindeal**

### CODE REVIEW

**Comment by AMDmi3** [comment]
Sorry, but repology policy is not to add private repositories.

**Comment by rindeal** [comment]
What do you mean by _private_?

**Comment by AMDmi3** [comment]
These maintained by a single person.

**Comment by rindeal** [comment]
Linuxunderground overlay is _private_ in your sense of the word yet it's there, but nevermind. Still maybe you could state the policy in some docs, so that others won't waste time like me.

**Comment by AMDmi3** [comment]
Fair enough, it will be removed.

**Pull request closed without merging**
