### PR TITLE
Add rules for webkit

### PR DESCRIPTION
**Pull request by pink-mist**
See #268 

I'm not entirely certain if this has any unintended matches.

There's also the following ones which I did not add rules for, and I'm unsure if they should be included or not:
* https://repology.org/metapackage/mingw:webkitgtk/versions
* https://repology.org/metapackage/mingw:webkitgtk3/versions

### CODE REVIEW

**Comment by AMDmi3** [comment]
Please put it into 45.splitmergever, also it's better to not use . (.?, .*) as it may have unintrnded matches (for example, something like webkitgtk-python). It's common practice to use limited regexp which matches version numbers and srparators, e.g. something like `(?:lib)?webkit[0-9._-]*gtk[0-9._-]*` plus additional rule for unstable with ignorever.

No, mingw32 may be ignored for now. The idea is to merge them all in one go as soon as flavors are implemented (so they compare properly against native packages).

**Comment by pink-mist** [comment]
Alright, I moved it over to 45 and reworked the pattern.

**Comment by pink-mist** [comment]
And now I also split out the -unstable one and set it to ignorever: true

**Comment by pink-mist** [comment]
Also added rules for qtwebkit

**Comment by AMDmi3** [comment]
Please simplify. `[0-9._-]*` may be used instead of any version-like sequence

**Comment by AMDmi3** [comment]
To speed this up, I've just added the rules. For qtwebkit we already have a common rule for qt packages webkit nicely fits into.

**Pull request closed without merging**
