### PR TITLE
Updated the pureos.yaml file

### PR DESCRIPTION
**Pull request by jeremiah**
Hi - thanks for repology! I'm updating our PureOS release name so you have an accurate package count.

### CODE REVIEW

**Comment by AMDmi3** [comment]
Thanks!

However, what's the difference between green and amber? Shouldn't it be added instead of replacing? Is landing still actual?

**Comment by jeremiah** [comment]
Thank you!

The difference is that 'green' was following Debian testing. We're going to turn 'green' into two distros, one following Debian stable and one following Debian testing. We put our packages on top but we try and keep a very small delta between us and Debian. We've created the code name amber for the stable and byzantium for the testing release. Amber is the one that's ready now.

**Comment by jeremiah** [comment]
Oh, yes, landing is still current (actual.) :+1:

**Comment by AMDmi3** [comment]
Thanks for clarification, looks good.

**Pull request merged**
