### PR TITLE
added Ataraxia Linux repository

### PR DESCRIPTION
**Pull request by protonesso**
It works!
Screenshot at 2019-08-31 12-42-48

### CODE REVIEW

**Comment by AMDmi3** [comment]
I lean towards not accepting unreliable parsing of shell build files any more. Existing repositories will be removed at some point too. In this case, this prevents parsing at least 4 packages, providing incomplete repository data.

If I'm not mistaken, you're founder of this distro, can't you set up a regular machine readable dump of package information? Apart from providing complete information, even for packages with variable substitutions in name/version, it could also include additional data such as `source` field (Repology would report broken ones with this). Details on possible dump format can be found at https://repology.org/addrepo.

**Comment by protonesso** [comment]
Will you remove crux?

**Comment by protonesso** [comment]
Also, where should I provide dump?

**Comment by AMDmi3** [comment]
> Will you remove crux?

Not right now, but in foreseeable future - as Repology evolves, quality requirements to data sources increase, and a parser which doesn't parse all packages from a repository will surely become unacceptable at some point.

> Also, where should I provide dump?

Anywhere you like or can, as long as it's reachable by Repology.

**Comment by protonesso** [comment]
So I just can send you parsed data?

**Comment by AMDmi3** [comment]
Depends on what you mean by "send".

**Comment by protonesso** [comment]
Send archive with parsed data on your server. Or you can say how can I
provide it.

**Comment by AMDmi3** [comment]
I need a regularly updated data accessible somewhere on the web.

**Comment by protonesso** [comment]
Okay

**Comment by AMDmi3** [comment]
Timeout

**Comment by protonesso** [comment]
@AMDmi3 ok. now can you parse this kind of file?
https://github.com/ataraxialinux/ataraxia/blob/master/packages/repo

first word - package name
second word - package version
third word - package release

**Comment by AMDmi3** [comment]
I need JSON with more data (+Description, URL, preferrably Maintainer, Depends, Section and interpolated `source`s)

**Comment by protonesso** [comment]
ok, I will try tomorrow

**Comment by protonesso** [comment]
@AMDmi3 just in case, can you send example of json data?

**Comment by AMDmi3** [comment]
I've given a link to documentation above.

**Comment by protonesso** [comment]
@AMDmi3 done!
 File location: https://github.com/ataraxialinux/ataraxia/blob/master/packages/repo

**Comment by AMDmi3** [comment]
This is great! Few minor issues remaining:
- What about downloads?
- You can drop `license` field from json if there's nothing to fill them with
- Just to be sure: are package names guaranteed to match package directory names? Cause otherwise generated links to recipes may be broken.
- Found a case of problematic naming: [createrepo](https://github.com/ataraxialinux/ataraxia/blob/master/packages/createrepo/KagamiBuild) is in fact `createrepo_c` and would [clash](https://repology.org/projects/?search=createrepo&maintainer=&category=&inrepo=&notinrepo=&repos=&families=&repos_newest=&families_newest=) with real `createrepo`
- Found a case of problematic version: [tcc](
https://github.com/ataraxialinux/ataraxia/blob/master/packages/tcc/KagamiBuild#L7) uses snapshot and announces it as a nonexisting version. Would be nice if information on this could be exposed to json. If using `commit` variable is common patter, it could be just added to the json.
- Found a case I'm not sure how to handle: [fuse-common](https://github.com/ataraxialinux/ataraxia/blob/master/packages/fuse-common/KagamiBuild) which is merged with fuse (many repos have fuse-common which is actually a part of fuse), but version is incompatible. If there's no viable solution on your side, I can just split it from fuse or ignore the version.

**Comment by protonesso** [comment]
> What about downloads?
working on it
>createrepo_c
ok, renaming
>tcc
I should use version.commit (0.9.28.e371642) or just hash?
>fuse-common
Configs for fuse, I don't want to make conflicts between fuse and fuse2 packages since they use same config

**Comment by protonesso** [comment]
createrepo_c, tcc and sources are fixed

**Comment by protonesso** [comment]
>Just to be sure: are package names guaranteed to match package directory names? Cause otherwise generated links to recipes may be broken.

Sometimes I have to adjust directory names

**Comment by AMDmi3** [comment]
> Sometimes I have to adjust directory names

Does in mean yes or no?

**Comment by AMDmi3** [comment]
One final problem - maintainers are not parsed because unexpected format is used (`protonesso nagakamira@gmail.com` instead of `protonesso <nagakamira@gmail.com>`). Meanwhile it's deployed and will appear on the site in couple of hours.

**Comment by protonesso** [comment]
Can I just put my email?

2020年5月18日(月) 20:12 Dmitry Marakasov <notifications@github.com>:

**Comment by AMDmi3** [comment]
> Can I just put my email?

Sure. Or just add a comma `protonesso, nagakamira@gmail.com`.
The thing is that Repology avoids parsing emails which are surrounded by extra words as this may bring in garbage, e.g. in case of obfuscated emails like `john dot doe@example dot com`

**Comment by AMDmi3** [comment]
FYI, json is currently broken by comma before the end of the list.

**Comment by protonesso** [comment]
I was on phone that time, let me fix that

2020年5月19日(火) 2:54 Dmitry Marakasov <notifications@github.com>:

**Pull request closed without merging**
